# Nginx reverse proxy configuration
# Routes traffic to frontend and backend services
# Usage: docker-compose -f docker-compose.yml -f docker-compose.nginx.yml up

version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: bakery_nginx
    ports:
      - "${NGINX_PORT:-80}:80"
      - "${NGINX_SSL_PORT:-443}:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./docker/nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - bakery_network
    restart: unless-stopped