# Production overrides for Docker Compose
# Adds production optimizations, security settings, and restart policies
# Usage: docker-compose -f docker-compose.yml -f docker-compose.database.yml -f docker-compose.app.yml -f docker-compose.nginx.yml -f docker-compose.prod.yml up

version: '3.8'

services:
  postgres:
    restart: always
    environment:
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=en_US.utf8 --lc-ctype=en_US.utf8"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G

  redis:
    restart: always
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-}
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M

  backend:
    restart: always
    environment:
      ENVIRONMENT: production
      LOG_LEVEL: INFO
      WORKERS: 4
    command: uvicorn main:app --host 0.0.0.0 --port 5000 --workers 4
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    restart: always
    environment:
      NODE_ENV: production
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./docker/nginx/ssl:/etc/nginx/ssl:ro
      - ./docker/nginx/cache:/var/cache/nginx
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  pgadmin:
    restart: always
    profiles:
      - tools  # Only start when explicitly requested